Complete the update of Scoreboard-related XML and JAVA files. However, the app crashed when the user finished the game from whatever mode it was in, and it also crashed when viewing the scoreboard to check the user's game data.
Bugs that have caused this:
android.database.sqlite.SQLiteException: no such column: mode (code 1 SQLITE_ERROR): , while compiling: SELECT id, username, score, mode, date FROM scoreBoard

Lines of code responsible for the bugs:
        at com.myapplicationdev.android.fyp.Utilities.DBHelper.getAllScoreBoard(DBHelper.java:132)
        at com.myapplicationdev.android.fyp.Questions.EasyQuestionsActivity.finishQuiz(EasyQuestionsActivity.java:380)
        at com.myapplicationdev.android.fyp.Questions.EasyQuestionsActivity.lambda$checkAnswer$9$EasyQuestionsActivity(EasyQuestionsActivity.java:256)